"use client";

import { Check, Eye, LockKeyhole, ShieldBan, Undo2, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { Pagination } from "@/components/common/Pagination";
import { useAppModal } from "@/components/ui/app-modal";
import { formatCurrency } from "@/lib/format";
import { adminService } from "@/services/admin.service";
import { getApiErrorMessage } from "@/services/api";
import type { AdminProduct, AdminShop, AdminUser, PageResponse } from "@/types";
import { AdminError, AdminLoading, AdminPageHeader, AdminStatus, AdminToolbar, EmptyRow } from "./AdminUi";

const PAGE_SIZE=15;
type ListParams={keyword:string;status:string;page:number;size:number};
const userLoader=(params:ListParams)=>adminService.users(params);
const shopLoader=(params:ListParams)=>adminService.shops(params);
const productLoader=(params:ListParams)=>adminService.products(params);
const USER_STATUSES=[{value:"ACTIVE",label:"Hoạt động"},{value:"SUSPENDED",label:"Tạm khóa"},{value:"BANNED",label:"Cấm"}] as const;
const SHOP_STATUSES=[{value:"PENDING",label:"Chờ duyệt"},{value:"ACTIVE",label:"Hoạt động"},{value:"REJECTED",label:"Từ chối"},{value:"BANNED",label:"Đã khóa"}] as const;
const PRODUCT_STATUSES=[{value:"ACTIVE",label:"Đang bán"},{value:"INACTIVE",label:"Seller tạm dừng"},{value:"BANNED",label:"Admin đã ẩn"}] as const;

interface PagedProps<T>{eyebrow:string;title:string;description:string;columns:string[];statuses:readonly {value:string;label:string}[];loader:(params:ListParams)=>Promise<PageResponse<T>>;row:(item:T,reload:()=>void)=>ReactNode;rowKey:(item:T)=>number|string}
function PagedAdminScreen<T>({eyebrow,title,description,columns,statuses,loader,row,rowKey}:PagedProps<T>){
  const [keyword,setKeyword]=useState("");const [status,setStatus]=useState("");const [page,setPage]=useState(0);const [reload,setReload]=useState(0);
  const requestKey=`${keyword.trim()}|${status}|${page}|${reload}`;
  const [state,setState]=useState<{key:string;data:PageResponse<T>|null;error:string|null}>({key:"",data:null,error:null});
  useEffect(()=>{let ignored=false;const timer=window.setTimeout(()=>{loader({keyword:keyword.trim(),status,page,size:PAGE_SIZE}).then(data=>{if(!ignored)setState({key:requestKey,data,error:null})}).catch(error=>{if(!ignored)setState({key:requestKey,data:null,error:getApiErrorMessage(error)})})},250);return()=>{ignored=true;window.clearTimeout(timer)}},[keyword,loader,page,reload,requestKey,status]);
  const current=state.key===requestKey;
  return <main className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8"><AdminPageHeader eyebrow={eyebrow} title={title} description={description}/><AdminToolbar keyword={keyword} onKeywordChange={v=>{setKeyword(v);setPage(0)}} status={status} onStatusChange={v=>{setStatus(v);setPage(0)}} statuses={statuses} loading={!current} onReload={()=>setReload(v=>v+1)}/>{!current?<AdminLoading/>:state.error||!state.data?<AdminError message={state.error||"Không có dữ liệu"} onRetry={()=>setReload(v=>v+1)}/>:<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr>{columns.map(c=><th key={c} className="px-4 py-3 font-black">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{state.data.data.length?state.data.data.map(item=><tr key={rowKey(item)} className="hover:bg-slate-50/70">{row(item,()=>setReload(v=>v+1))}</tr>):<EmptyRow colSpan={columns.length}/>}</tbody></table></div><div className="border-t border-slate-100 px-4 pb-5"><p className="pt-3 text-xs text-slate-400">Tổng {state.data.totalElements.toLocaleString("vi-VN")} bản ghi</p><Pagination currentPage={state.data.currentPage} totalPages={state.data.totalPages} onPageChange={setPage}/></div></section>}</main>;
}

export function AdminUsersScreen(){const modal=useAppModal();async function action(user:AdminUser,reload:()=>void,status:string){const restricted=status!=="ACTIVE";const reason=restricted?window.prompt("Nhập lý do khóa tài khoản:")||"":undefined;if(restricted&&!reason)return;const ok=await modal.confirm({title:status==="ACTIVE"?"Mở khóa tài khoản?":"Khóa tài khoản?",description:`@${user.username||user.email}`,danger:restricted});if(!ok)return;try{await adminService.changeUserStatus(user.id,status,reason);modal.showSuccess({title:"Đã cập nhật tài khoản"});reload()}catch(e){modal.showError({title:"Không thể cập nhật",description:getApiErrorMessage(e)})}}
return <PagedAdminScreen eyebrow="Danh tính & phân quyền" title="Người dùng" description="Tra cứu buyer, seller và quản trị viên; khóa phiên đăng nhập khi tài khoản bị hạn chế." columns={["Người dùng","Vai trò","Cấp độ","Chi tiêu / doanh thu","Trạng thái","Hoạt động cuối","Thao tác"]} statuses={USER_STATUSES} loader={userLoader} rowKey={u=>u.id} row={(u,reload)=><><td className="px-4 py-4"><b className="text-slate-900">{u.fullName}</b><p className="text-xs text-slate-500">@{u.username||"chưa-có"} · {u.email}</p></td><td className="px-4 py-4 font-bold text-violet-700">{u.role}</td><td className="px-4 py-4">LV.{u.level}</td><td className="px-4 py-4 text-xs"><p>{formatCurrency(u.accumulatedSpent)}</p><p className="text-emerald-700">{formatCurrency(u.accumulatedEarned)}</p></td><td className="px-4 py-4"><AdminStatus value={u.status}/>{u.banReason?<p className="mt-1 max-w-44 truncate text-[10px] text-rose-500" title={u.banReason}>{u.banReason}</p>:null}</td><td className="px-4 py-4 text-xs text-slate-500">{dateTime(u.lastActiveAt)}</td><td className="px-4 py-4">{u.role!=="SUPER_ADMIN"?(u.status==="ACTIVE"?<ActionButton title="Khóa" danger onClick={()=>action(u,reload,"SUSPENDED")} icon={LockKeyhole}/>:<ActionButton title="Mở" onClick={()=>action(u,reload,"ACTIVE")} icon={Undo2}/>):"—"}</td></>}/>}

export function AdminShopsScreen(){const modal=useAppModal();async function action(shop:AdminShop,reload:()=>void,status:string){const needsReason=status==="REJECTED"||status==="BANNED";const reason=needsReason?window.prompt("Nhập lý do xử lý gian hàng:")||"":undefined;if(needsReason&&!reason)return;const ok=await modal.confirm({title:status==="ACTIVE"?"Duyệt/kích hoạt gian hàng?":status==="REJECTED"?"Từ chối hồ sơ?":"Khóa gian hàng?",description:shop.name,danger:status!=="ACTIVE"});if(!ok)return;try{await adminService.changeShopStatus(shop.id,status,reason,shop.version);modal.showSuccess({title:"Đã cập nhật gian hàng"});reload()}catch(e){modal.showError({title:"Không thể xử lý",description:getApiErrorMessage(e)})}}
return <PagedAdminScreen eyebrow="Seller onboarding" title="Duyệt gian hàng" description="Duyệt hồ sơ là đường duy nhất chuyển BUYER thành SELLER và đồng bộ tên shop." columns={["Gian hàng","Chủ sở hữu","Sản phẩm","Đã bán","Uy tín","Trạng thái","Thao tác"]} statuses={SHOP_STATUSES} loader={shopLoader} rowKey={s=>s.id} row={(s,reload)=><><td className="px-4 py-4"><b>{s.name}</b><p className="text-xs text-slate-400">/{s.slug}</p></td><td className="px-4 py-4"><p>@{s.ownerUsername||"—"}</p><p className="text-xs text-slate-400">{s.ownerEmail}</p></td><td className="px-4 py-4">{s.productCount}</td><td className="px-4 py-4">{s.soldCount}</td><td className="px-4 py-4 text-xs">{s.ratingCount?`${s.ratingAvg.toFixed(1)} ★ (${s.ratingCount})`:"Mới"}<p className="text-slate-400">Khiếu nại {s.disputeRate}%</p></td><td className="px-4 py-4"><AdminStatus value={s.status}/></td><td className="px-4 py-4"><div className="flex gap-2">{s.status==="PENDING"?<><ActionButton title="Duyệt" onClick={()=>action(s,reload,"ACTIVE")} icon={Check}/><ActionButton title="Từ chối" danger onClick={()=>action(s,reload,"REJECTED")} icon={X}/></>:s.status==="ACTIVE"?<ActionButton title="Khóa" danger onClick={()=>action(s,reload,"BANNED")} icon={ShieldBan}/>:<ActionButton title="Kích hoạt" onClick={()=>action(s,reload,"ACTIVE")} icon={Undo2}/>}</div></td></>}/>}

export function AdminProductsScreen(){const modal=useAppModal();async function action(product:AdminProduct,reload:()=>void,status:string){const reason=status==="BANNED"?window.prompt("Nhập lý do ẩn sản phẩm:")||"":undefined;if(status==="BANNED"&&!reason)return;const ok=await modal.confirm({title:status==="ACTIVE"?"Khôi phục sản phẩm?":"Ẩn sản phẩm khỏi sàn?",description:product.name,danger:status==="BANNED"});if(!ok)return;try{await adminService.changeProductStatus(product.id,status,reason);modal.showSuccess({title:"Đã cập nhật sản phẩm"});reload()}catch(e){modal.showError({title:"Không thể xử lý",description:getApiErrorMessage(e)})}}
return <PagedAdminScreen eyebrow="Post-moderation" title="Kiểm duyệt sản phẩm" description="Sản phẩm được đăng ngay; admin có thể ẩn vi phạm bằng BANNED và seller không tự bật lại được." columns={["Sản phẩm","Gian hàng","Danh mục","Loại giao","Giá / tồn","Đã bán","Trạng thái","Thao tác"]} statuses={PRODUCT_STATUSES} loader={productLoader} rowKey={p=>p.id} row={(p,reload)=><><td className="px-4 py-4"><b>{p.name}</b><p className="text-xs text-slate-400">#{p.id}</p></td><td className="px-4 py-4">{p.shopName}</td><td className="px-4 py-4">{p.categoryName}</td><td className="px-4 py-4 font-bold text-violet-700">{p.deliveryType==="INSTANT"?"Giao ngay":"Đặt hàng"}</td><td className="px-4 py-4 text-xs"><p>{p.minPrice==null?"—":formatCurrency(p.minPrice)}</p><p className="text-slate-400">Tồn {p.stockCount}</p></td><td className="px-4 py-4">{p.soldCount}</td><td className="px-4 py-4"><AdminStatus value={p.status}/></td><td className="px-4 py-4"><div className="flex gap-2"><Link href={`/products/${p.slug}`} title="Xem sản phẩm" className="grid size-9 place-items-center rounded-lg border border-slate-200 text-slate-600"><Eye className="size-4"/></Link>{p.status==="BANNED"?<ActionButton title="Khôi phục" onClick={()=>action(p,reload,"ACTIVE")} icon={Undo2}/>:<ActionButton title="Ẩn" danger onClick={()=>action(p,reload,"BANNED")} icon={ShieldBan}/>}</div></td></>}/>}

function ActionButton({title,onClick,icon:Icon,danger=false}:{title:string;onClick:()=>void;icon:typeof Check;danger?:boolean}){return <button type="button" title={title} onClick={onClick} className={`grid size-9 place-items-center rounded-lg border ${danger?"border-rose-200 bg-rose-50 text-rose-600":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}><Icon className="size-4"/></button>}
function dateTime(value:string|null){return value?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—"}
