"use client";

import { Check, X } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Pagination } from "@/components/common/Pagination";
import { useAppModal } from "@/components/ui/app-modal";
import { formatCurrency } from "@/lib/format";
import { adminService } from "@/services/admin.service";
import { getApiErrorMessage } from "@/services/api";
import type { AdminDeposit, AdminWalletTransaction, AdminWithdrawal, PageResponse } from "@/types";
import { AdminError, AdminLoading, AdminPageHeader, AdminStatus, AdminToolbar, EmptyRow } from "./AdminUi";

const SIZE=15;type Params={keyword:string;status:string;page:number;size:number};
interface Props<T>{eyebrow:string;title:string;description:string;columns:string[];statuses:readonly {value:string;label:string}[];loader:(p:Params)=>Promise<PageResponse<T>>;row:(item:T,reload:()=>void)=>ReactNode;keyOf:(item:T)=>string|number}
function MoneyScreen<T>({eyebrow,title,description,columns,statuses,loader,row,keyOf}:Props<T>){const [keyword,setKeyword]=useState("");const[status,setStatus]=useState("");const[page,setPage]=useState(0);const[reload,setReload]=useState(0);const key=`${keyword}|${status}|${page}|${reload}`;const[state,setState]=useState<{key:string;data:PageResponse<T>|null;error:string|null}>({key:"",data:null,error:null});useEffect(()=>{let ignored=false;const timer=window.setTimeout(()=>loader({keyword:keyword.trim(),status,page,size:SIZE}).then(data=>{if(!ignored)setState({key,data,error:null})}).catch(e=>{if(!ignored)setState({key,data:null,error:getApiErrorMessage(e)})}),250);return()=>{ignored=true;window.clearTimeout(timer)}},[key,keyword,loader,page,status]);const current=state.key===key;return <main className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8"><AdminPageHeader eyebrow={eyebrow} title={title} description={description}/><AdminToolbar keyword={keyword} onKeywordChange={v=>{setKeyword(v);setPage(0)}} status={status} onStatusChange={v=>{setStatus(v);setPage(0)}} statuses={statuses} loading={!current} onReload={()=>setReload(v=>v+1)}/>{!current?<AdminLoading/>:state.error||!state.data?<AdminError message={state.error||"Không có dữ liệu"} onRetry={()=>setReload(v=>v+1)}/>:<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr>{columns.map(c=><th key={c} className="px-4 py-3 font-black">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{state.data.data.length?state.data.data.map(i=><tr key={keyOf(i)} className="hover:bg-slate-50">{row(i,()=>setReload(v=>v+1))}</tr>):<EmptyRow colSpan={columns.length}/>}</tbody></table></div><div className="border-t border-slate-100 px-4 pb-5"><p className="pt-3 text-xs text-slate-400">Tổng {state.data.totalElements.toLocaleString("vi-VN")} bản ghi</p><Pagination currentPage={state.data.currentPage} totalPages={state.data.totalPages} onPageChange={setPage}/></div></section>}</main>}

const depositLoader=(p:Params)=>adminService.deposits(p);
const withdrawalLoader=(p:Params)=>adminService.withdrawals(p);
const transactionLoader=(p:Params)=>adminService.transactions({keyword:p.keyword,type:p.status,page:p.page,size:p.size});
const DEPOSITS=["PENDING","SUCCESS","REVIEW_REQUIRED","FAILED","EXPIRED"].map(v=>({value:v,label:v.replaceAll("_"," ")}));
const WITHDRAWALS=["PENDING","DONE","REJECTED"].map(v=>({value:v,label:v}));
const TRANSACTIONS=["DEPOSIT","ORDER_PAYMENT","SALE_HOLD","HOLD_RELEASE_NET","PLATFORM_FEE","ORDER_REFUND","DISPUTE_REFUND","WITHDRAW_PENDING","WITHDRAW_DONE","WITHDRAW_CANCEL","ADMIN_ADJUST"].map(v=>({value:v,label:v.replaceAll("_"," ")}));

export function AdminDepositsScreen(){return <MoneyScreen eyebrow="Đối soát đầu vào" title="Trạng thái nạp tiền" description="Theo dõi giao dịch SePay, mã thanh toán và các khoản cần kiểm tra thủ công." columns={["Mã nạp","Người dùng","Số tiền","Nhà cung cấp","Mã ngân hàng","Trạng thái","Tạo lúc","Thanh toán lúc"]} statuses={DEPOSITS} loader={depositLoader} keyOf={d=>d.id} row={(d:AdminDeposit)=><><td className="px-4 py-4 font-mono text-xs">{d.transactionCode||`#${d.id}`}</td><td className="px-4 py-4"><b>@{d.username||"—"}</b><p className="text-xs text-slate-400">{d.email}</p></td><td className="px-4 py-4 font-black text-emerald-700">{formatCurrency(d.amount)}</td><td className="px-4 py-4">{d.provider}</td><td className="px-4 py-4 font-mono text-xs">{d.providerTransactionId||"—"}</td><td className="px-4 py-4"><AdminStatus value={d.status}/></td><td className="px-4 py-4 text-xs">{dt(d.createdAt)}</td><td className="px-4 py-4 text-xs">{dt(d.paidAt)}</td></>}/>}

export function AdminWithdrawalsScreen(){const modal=useAppModal();async function decide(item:AdminWithdrawal,reload:()=>void,action:"APPROVE"|"REJECT"){const note=window.prompt(action==="APPROVE"?"Ghi chú chuyển khoản (không bắt buộc):":"Nhập lý do từ chối:")||"";if(action==="REJECT"&&!note)return;const ok=await modal.confirm({title:action==="APPROVE"?"Xác nhận đã chuyển tiền?":"Từ chối yêu cầu rút?",description:`${item.accountName} · ${formatCurrency(item.amount)}`,danger:action==="REJECT"});if(!ok)return;try{await adminService.decideWithdrawal(item.id,action,note||undefined);modal.showSuccess({title:"Đã xử lý yêu cầu rút tiền"});reload()}catch(e){modal.showError({title:"Không thể xử lý",description:getApiErrorMessage(e)})}}return <MoneyScreen eyebrow="Payout seller" title="Yêu cầu rút tiền" description="Duyệt sau khi đã chuyển khoản thực tế; từ chối sẽ hoàn tiền nguyên tử về ví người dùng." columns={["ID","Người nhận","Số tiền","Ngân hàng","Số tài khoản","Tên tài khoản","Trạng thái","Tạo lúc","Thao tác"]} statuses={WITHDRAWALS} loader={withdrawalLoader} keyOf={w=>w.id} row={(w:AdminWithdrawal,reload)=><><td className="px-4 py-4 font-mono">#{w.id}</td><td className="px-4 py-4"><b>@{w.username||"—"}</b><p className="text-xs text-slate-400">{w.email}</p></td><td className="px-4 py-4 font-black">{formatCurrency(w.amount)}</td><td className="px-4 py-4">{w.bankName}</td><td className="px-4 py-4 font-mono">{w.accountNumber}</td><td className="px-4 py-4">{w.accountName}</td><td className="px-4 py-4"><AdminStatus value={w.status}/></td><td className="px-4 py-4 text-xs">{dt(w.createdAt)}</td><td className="px-4 py-4">{w.status==="PENDING"?<div className="flex gap-2"><button title="Duyệt" onClick={()=>decide(w,reload,"APPROVE")} className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Check className="size-4"/></button><button title="Từ chối" onClick={()=>decide(w,reload,"REJECT")} className="grid size-9 place-items-center rounded-lg bg-rose-50 text-rose-700"><X className="size-4"/></button></div>:<span className="text-xs text-slate-400">{w.processorUsername?`bởi @${w.processorUsername}`:"—"}</span>}</td></>}/>}

export function AdminTransactionsScreen(){return <MoneyScreen eyebrow="Sổ cái toàn sàn" title="Wallet Transactions" description="Truy vết mọi biến động số dư theo user, mã đơn/mã nạp và loại nghiệp vụ." columns={["Mã giao dịch","Người dùng","Loại","Số dư","Biến động","Trước → sau","Tham chiếu","Thời gian"]} statuses={TRANSACTIONS} loader={transactionLoader} keyOf={t=>t.id} row={(t:AdminWalletTransaction)=><><td className="max-w-36 truncate px-4 py-4 font-mono text-[11px]" title={t.id}>{t.id}</td><td className="px-4 py-4"><b>@{t.username||"PLATFORM"}</b><p className="text-xs text-slate-400">{t.email||`Ví #${t.walletId}`}</p></td><td className="px-4 py-4"><AdminStatus value={t.transactionType}/></td><td className="px-4 py-4 text-xs">{t.balanceType}</td><td className={`px-4 py-4 font-black ${t.amount>=0?"text-emerald-700":"text-rose-600"}`}>{t.amount>0?"+":""}{formatCurrency(t.amount)}</td><td className="px-4 py-4 text-xs">{formatCurrency(t.balanceBefore)} → {formatCurrency(t.balanceAfter)}</td><td className="px-4 py-4"><p className="font-mono text-xs">{t.referenceCode||"—"}</p><p className="text-[10px] text-slate-400">{t.referenceType||""}</p></td><td className="px-4 py-4 text-xs">{dt(t.createdAt)}</td></>}/>}
function dt(value:string|null){return value?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—"}
