"use client";

import { Plus, Power, PowerOff } from "lucide-react";
import { useEffect, useState } from "react";
import { useAppModal } from "@/components/ui/app-modal";
import { adminService } from "@/services/admin.service";
import { getApiErrorMessage } from "@/services/api";
import type { AdminCategory } from "@/types";
import { AdminError, AdminLoading, AdminPageHeader, AdminStatus, EmptyRow } from "./AdminUi";

export function AdminCategoriesScreen(){
  const modal=useAppModal();const [reload,setReload]=useState(0);const [name,setName]=useState("");const [parentId,setParentId]=useState("");const [sortOrder,setSortOrder]=useState("0");const [saving,setSaving]=useState(false);
  const [state,setState]=useState<{key:number;data:AdminCategory[]|null;error:string|null}>({key:-1,data:null,error:null});
  useEffect(()=>{let ignored=false;adminService.categories().then(data=>{if(!ignored)setState({key:reload,data,error:null})}).catch(e=>{if(!ignored)setState({key:reload,data:null,error:getApiErrorMessage(e)})});return()=>{ignored=true}},[reload]);
  async function create(){if(!name.trim())return;setSaving(true);try{await adminService.createCategory({name:name.trim(),parentId:parentId?Number(parentId):undefined,sortOrder:Number(sortOrder)||0});setName("");setParentId("");setSortOrder("0");modal.showSuccess({title:"Đã tạo danh mục"});setReload(v=>v+1)}catch(e){modal.showError({title:"Không thể tạo danh mục",description:getApiErrorMessage(e)})}finally{setSaving(false)}}
  async function toggle(item:AdminCategory){const enable=!item.active;const ok=await modal.confirm({title:enable?"Bật lại danh mục?":"Ẩn danh mục?",description:enable?"Danh mục sẽ xuất hiện lại nếu danh mục cha cũng hoạt động.":"Sản phẩm thuộc danh mục sẽ không còn hiện công khai.",danger:!enable});if(!ok)return;try{if(enable)await adminService.updateCategory(item.id,{isActive:true});else await adminService.deactivateCategory(item.id);setReload(v=>v+1)}catch(e){modal.showError({title:"Không thể cập nhật",description:getApiErrorMessage(e)})}}
  const current=state.key===reload;
  return <main className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8"><AdminPageHeader eyebrow="Cấu trúc catalog" title="Quản lý danh mục" description="Admin tạo danh mục; shop chỉ được chọn danh mục đang hoạt động."/>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black text-slate-900">Thêm danh mục</h2><div className="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_140px_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên danh mục" className="h-11 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-violet-400"/><select value={parentId} onChange={e=>setParentId(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Danh mục gốc</option>{state.data?.filter(c=>c.parentId==null&&c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="number" min="0" value={sortOrder} onChange={e=>setSortOrder(e.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><button disabled={saving||!name.trim()} onClick={create} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-black text-white disabled:opacity-50"><Plus className="size-4"/>Thêm</button></div></section>
    {!current?<AdminLoading/>:state.error||!state.data?<AdminError message={state.error||"Không có dữ liệu"} onRetry={()=>setReload(v=>v+1)}/>:<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr>{["Danh mục","Cấp","Slug","Sắp xếp","Sản phẩm","Trạng thái","Thao tác"].map(c=><th key={c} className="px-4 py-3 font-black">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{state.data.length?state.data.map(c=><tr key={c.id} className="hover:bg-slate-50"><td className="px-4 py-4 font-bold text-slate-900">{c.parentId?<span className="mr-2 text-slate-300">└</span>:null}{c.name}</td><td className="px-4 py-4">{c.parentId?`Con của ${c.parentName}`:"Danh mục gốc"}</td><td className="px-4 py-4 text-xs text-slate-500">{c.slug}</td><td className="px-4 py-4">{c.sortOrder}</td><td className="px-4 py-4">{c.productCount}</td><td className="px-4 py-4"><AdminStatus value={c.active?"ACTIVE":"INACTIVE"}/></td><td className="px-4 py-4"><button onClick={()=>toggle(c)} title={c.active?"Ẩn":"Bật"} className={`grid size-9 place-items-center rounded-lg ${c.active?"bg-rose-50 text-rose-600":"bg-emerald-50 text-emerald-700"}`}>{c.active?<PowerOff className="size-4"/>:<Power className="size-4"/>}</button></td></tr>):<EmptyRow colSpan={7}/>}</tbody></table></div></section>}
  </main>;
}
