"use client";

import { useEffect, useState } from "react";
import { Pagination } from "@/components/common/Pagination";
import { adminService } from "@/services/admin.service";
import { getApiErrorMessage } from "@/services/api";
import type { AdminAuditLog, PageResponse } from "@/types";
import { AdminError, AdminLoading, AdminPageHeader, AdminStatus, AdminToolbar, EmptyRow } from "./AdminUi";

const SIZE=15;
export function AdminAuditScreen(){const[keyword,setKeyword]=useState("");const[targetType,setTargetType]=useState("");const[page,setPage]=useState(0);const[reload,setReload]=useState(0);const key=`${keyword}|${targetType}|${page}|${reload}`;const[state,setState]=useState<{key:string;data:PageResponse<AdminAuditLog>|null;error:string|null}>({key:"",data:null,error:null});useEffect(()=>{let ignored=false;const timer=window.setTimeout(()=>adminService.auditLogs({keyword:keyword.trim(),targetType,page,size:SIZE}).then(data=>{if(!ignored)setState({key,data,error:null})}).catch(e=>{if(!ignored)setState({key,data:null,error:getApiErrorMessage(e)})}),250);return()=>{ignored=true;window.clearTimeout(timer)}},[key,keyword,page,targetType]);const current=state.key===key;return <main className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8"><AdminPageHeader eyebrow="Accountability" title="Nhật ký quản trị" description="Ai đã tác động lên dữ liệu nào, trước/sau ra sao, từ IP và thiết bị nào."/><AdminToolbar keyword={keyword} onKeywordChange={v=>{setKeyword(v);setPage(0)}} status={targetType} onStatusChange={v=>{setTargetType(v);setPage(0)}} statuses={[{value:"USER",label:"User"},{value:"SHOP",label:"Shop"},{value:"PRODUCT",label:"Sản phẩm"},{value:"CATEGORY",label:"Danh mục"},{value:"DISPUTE",label:"Khiếu nại"},{value:"WITHDRAWAL",label:"Rút tiền"},{value:"FEE_CONFIG",label:"Cấu hình phí"}]} loading={!current} onReload={()=>setReload(v=>v+1)}/>{!current?<AdminLoading/>:state.error||!state.data?<AdminError message={state.error||"Không có dữ liệu"} onRetry={()=>setReload(v=>v+1)}/>:<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr>{["Thời gian","Quản trị viên","Hành động","Đối tượng","Lý do","Giá trị cũ","Giá trị mới","IP"].map(c=><th key={c} className="px-4 py-3">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{state.data.data.length?state.data.data.map(a=><tr key={a.id}><td className="px-4 py-4 text-xs">{dt(a.createdAt)}</td><td className="px-4 py-4"><b>@{a.actorUsername}</b><p className="text-xs text-slate-400">{a.actorRole}</p></td><td className="px-4 py-4"><AdminStatus value={a.action}/></td><td className="px-4 py-4 font-mono text-xs">{a.targetType} #{a.targetId}</td><td className="max-w-52 truncate px-4 py-4 text-xs" title={a.reason||""}>{a.reason||"—"}</td><JsonCell value={a.oldValue}/><JsonCell value={a.newValue}/><td className="px-4 py-4 font-mono text-xs">{a.ipAddress||"—"}</td></tr>):<EmptyRow colSpan={8}/>}</tbody></table></div><div className="px-4 pb-5"><Pagination currentPage={state.data.currentPage} totalPages={state.data.totalPages} onPageChange={setPage}/></div></section>}</main>}
function JsonCell({value}:{value:Record<string,unknown>|null}){const text=value?JSON.stringify(value):"—";return <td className="max-w-60 truncate px-4 py-4 font-mono text-[10px] text-slate-500" title={text}>{text}</td>}
function dt(value:string){return new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"medium"}).format(new Date(value))}
